
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador.Default.Compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REPITEHASTA = 48;
  public static final int DOSPUNTOS = 44;
  public static final int NUMERO = 12;
  public static final int OBJETODELANTE = 30;
  public static final int ELIMINAR = 22;
  public static final int CASO = 42;
  public static final int RANDOM = 52;
  public static final int PARENTESISCIERRA = 4;
  public static final int PUNTOYCOMA = 8;
  public static final int OPERADORARITMETICO = 15;
  public static final int PROGRAMA = 2;
  public static final int OPERADORLOGICO = 38;
  public static final int SI = 35;
  public static final int IZQUIERDA = 18;
  public static final int SEPARADOR = 10;
  public static final int OPERADORASIGNACION = 11;
  public static final int FIN = 43;
  public static final int OPERADORNEGACION = 50;
  public static final int ESPERA = 17;
  public static final int AVANZAR = 16;
  public static final int IDENTIFICADOR = 9;
  public static final int PARENTESISABRE = 3;
  public static final int SINO = 40;
  public static final int OPERADORARITMETICOSUMA = 13;
  public static final int COMPARAR = 41;
  public static final int QUETENGODELANTE = 32;
  public static final int TOMAR = 20;
  public static final int EOF = 0;
  public static final int LLAVEABRE = 5;
  public static final int error = 1;
  public static final int LLAVECIERRA = 6;
  public static final int PINTAR = 24;
  public static final int CADENA = 29;
  public static final int OPERADORARITMETICORESTA = 14;
  public static final int IMPRIMIRCADENA = 28;
  public static final int SOLTAR = 21;
  public static final int ERROR = 51;
  public static final int COLORES = 25;
  public static final int REPITE = 49;
  public static final int OPERADORDECOMPARACION = 37;
  public static final int DERECHA = 19;
  public static final int VARIABLE = 7;
  public static final int DEFAULT = 45;
  public static final int DESACTIVARKABOOM = 23;
  public static final int HACER = 47;
  public static final int BOOLEANO = 36;
  public static final int KABOOMDEFRENTE = 31;
  public static final int IMPRIMIRVARIABLE = 27;
  public static final int PARA = 46;
  public static final int MURODELANTE = 33;
  public static final int SINOSI = 39;
  public static final int TERMINARBLOQUE = 34;
  public static final int DEJAPINTAR = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "VARIABLE",
  "PUNTOYCOMA",
  "IDENTIFICADOR",
  "SEPARADOR",
  "OPERADORASIGNACION",
  "NUMERO",
  "OPERADORARITMETICOSUMA",
  "OPERADORARITMETICORESTA",
  "OPERADORARITMETICO",
  "AVANZAR",
  "ESPERA",
  "IZQUIERDA",
  "DERECHA",
  "TOMAR",
  "SOLTAR",
  "ELIMINAR",
  "DESACTIVARKABOOM",
  "PINTAR",
  "COLORES",
  "DEJAPINTAR",
  "IMPRIMIRVARIABLE",
  "IMPRIMIRCADENA",
  "CADENA",
  "OBJETODELANTE",
  "KABOOMDEFRENTE",
  "QUETENGODELANTE",
  "MURODELANTE",
  "TERMINARBLOQUE",
  "SI",
  "BOOLEANO",
  "OPERADORDECOMPARACION",
  "OPERADORLOGICO",
  "SINOSI",
  "SINO",
  "COMPARAR",
  "CASO",
  "FIN",
  "DOSPUNTOS",
  "DEFAULT",
  "PARA",
  "HACER",
  "REPITEHASTA",
  "REPITE",
  "OPERADORNEGACION",
  "ERROR",
  "RANDOM"
  };
}

